# Generated by Django 4.1.3 on 2023-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="teacherclasscode",
            field=models.CharField(
                default="asdfasdfasdfasdfasdfasdf", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
