# Generated by Django 4.1.3 on 2023-03-14 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_class_teacherclasscode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classowner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
