# Generated by Django 4.1.3 on 2023-03-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_class_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herd",
            name="connectedclass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_herd_connectedclass",
                to="base.class",
            ),
        ),
    ]
