# Generated by Django 4.1.3 on 2023-03-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_herd_connectedclass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bull",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cow",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
