# Generated by Django 4.1.3 on 2023-03-19 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_bull_name_alter_cow_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="bull",
            name="dam",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.cow",
            ),
        ),
        migrations.AddField(
            model_name="bull",
            name="sire",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.bull",
            ),
        ),
        migrations.AddField(
            model_name="cow",
            name="dam",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.cow",
            ),
        ),
        migrations.AddField(
            model_name="cow",
            name="sire",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.bull",
            ),
        ),
    ]
