# Generated by Django 4.1.3 on 2023-03-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_bull_dam_bull_sire_cow_dam_cow_sire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correlation",
            name="oppose",
        ),
        migrations.AddField(
            model_name="correlation",
            name="factor",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
