# Generated by Django 4.1.3 on 2023-03-24 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_correlation_oppose_correlation_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="herd",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_herd_enrollment",
                to="base.enrollment",
            ),
        ),
    ]
