# Generated by Django 4.1.3 on 2023-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_class_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("info", models.TextField(max_length=1000)),
            ],
        ),
    ]
