# Generated by Django 4.1.3 on 2023-03-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_remove_resource_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticDataClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("data", models.TextField(max_length=1000)),
            ],
        ),
    ]
