# Generated by Django 4.1.3 on 2023-03-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_rename_title_staticdataclass_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaticDataClass",
        ),
    ]
