# Generated by Django 4.1.3 on 2023-04-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_delete_staticdataclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="traitslist",
            name="scaled",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
