# Generated by Django 4.1.3 on 2023-04-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_traitslist_scaled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bull",
            name="traits",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Bull_traits_TraitsList",
                to="base.traitslist",
            ),
        ),
        migrations.AlterField(
            model_name="cow",
            name="traits",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Cull_traits_TraitsList",
                to="base.traitslist",
            ),
        ),
    ]
