# Generated by Django 4.2 on 2023-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_alter_bull_traits_alter_cow_traits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.AddField(
            model_name="traitslist",
            name="recessives",
            field=models.JSONField(default={"none": None}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Correlation",
        ),
        migrations.DeleteModel(
            name="Trait",
        ),
    ]
