# Generated by Django 4.2 on 2023-05-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_alter_class_options_traitslist_recessives_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedagree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_id", models.CharField(max_length=255)),
                ("male", models.BooleanField()),
                (
                    "dam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_dam",
                        to="base.pedagree",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_sire",
                        to="base.pedagree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bovine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("scaled", models.JSONField()),
                ("recessives", models.JSONField()),
                (
                    "connected_bull",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_connected_bull",
                        to="base.bull",
                    ),
                ),
                (
                    "connected_cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_connected_cow",
                        to="base.cow",
                    ),
                ),
                (
                    "pedagree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.pedagree"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bull",
            name="traits",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Bull_traits_TraitsList",
                to="base.bovine",
            ),
        ),
        migrations.AlterField(
            model_name="cow",
            name="traits",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Cull_traits_TraitsList",
                to="base.bovine",
            ),
        ),
        migrations.DeleteModel(
            name="TraitsList",
        ),
    ]
