# Generated by Django 4.2 on 2023-05-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_pedagree_bovine_alter_bull_traits_alter_cow_traits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="connected_bull",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_connected_bull",
                to="base.bull",
            ),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="connected_cow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_connected_cow",
                to="base.cow",
            ),
        ),
        migrations.AlterField(
            model_name="pedagree",
            name="male",
            field=models.BooleanField(null=True),
        ),
    ]
