# Generated by Django 4.2 on 2023-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_bovine_connected_bull_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedagree",
            name="animal_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pedagree",
            name="dam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_dam",
                to="base.pedagree",
            ),
        ),
        migrations.AlterField(
            model_name="pedagree",
            name="sire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_sire",
                to="base.pedagree",
            ),
        ),
    ]
