# Generated by Django 4.2 on 2023-05-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_pedagree_animal_id_alter_pedagree_dam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="connected_bull",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_connected_bull",
                to="base.bull",
            ),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="connected_cow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_connected_cow",
                to="base.cow",
            ),
        ),
    ]
