# Generated by Django 4.2 on 2023-05-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_alter_bovine_connected_bull_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pedagree",
            new_name="Pedigree",
        ),
        migrations.RenameField(
            model_name="bovine",
            old_name="pedagree",
            new_name="pedigree",
        ),
    ]
