# Generated by Django 4.2 on 2023-05-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_rename_pedagree_pedigree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedigree",
            name="inbreeding",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
