# Generated by Django 4.2 on 2023-05-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_pedigree_inbreeding"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
