# Generated by Django 4.2 on 2023-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_remove_cow_dam_remove_cow_herd_remove_cow_sire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="data",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="recessives",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="scaled",
            field=models.JSONField(default={}),
        ),
    ]
