# Generated by Django 4.2 on 2023-05-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_alter_bovine_data_alter_bovine_recessives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="recessives",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="bovine",
            name="scaled",
            field=models.JSONField(default=dict),
        ),
    ]
