# Generated by Django 4.2 on 2023-05-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_alter_bovine_data_alter_bovine_recessives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="pedigree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.pedigree",
            ),
        ),
    ]
