# Generated by Django 4.2 on 2023-05-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_alter_bovine_male_alter_bovine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedigree",
            name="animal_id",
            field=models.CharField(default=153, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedigree",
            name="dam",
            field=models.ForeignKey(
                default=800,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_dam",
                to="base.pedigree",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedigree",
            name="male",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pedigree",
            name="sire",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_sire",
                to="base.pedigree",
            ),
            preserve_default=False,
        ),
    ]
