# Generated by Django 4.2 on 2023-05-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_alter_pedigree_animal_id_alter_pedigree_dam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedigree",
            name="dam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_dam",
                to="base.pedigree",
            ),
        ),
        migrations.AlterField(
            model_name="pedigree",
            name="sire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_sire",
                to="base.pedigree",
            ),
        ),
    ]
