# Generated by Django 4.2 on 2023-05-23 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_remove_herd_unrestricted"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="publicherd",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classpublicherd",
                to="base.herd",
            ),
            preserve_default=False,
        ),
    ]
