# Generated by Django 4.2 on 2023-06-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_remove_bovine_pedigree_bovine_dam_bovine_inbreeding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="inbreeding",
            field=models.FloatField(null=True),
        ),
    ]
