# Generated by Django 4.2 on 2023-06-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0043_alter_bovine_inbreeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="bovine",
            name="connectedclass",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="base.class"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bovine",
            name="herd",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.herd"
            ),
        ),
    ]
