# Generated by Django 4.2 on 2023-06-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0045_remove_bovine_connectedclass_alter_bovine_dam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bovine",
            name="pedigree",
        ),
        migrations.DeleteModel(
            name="Pedigree",
        ),
    ]
