# Generated by Django 4.2 on 2023-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0048_bovine_pedigree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bovine",
            name="pedigree",
            field=models.JSONField(null=True),
        ),
    ]
