# Generated by Django 4.2 on 2023-11-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0049_alter_bovine_pedigree"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="traitset",
            field=models.CharField(
                choices=[("0", "NM_2020")], default="0", max_length=20, null=True
            ),
        ),
    ]
