# Generated by Django 4.2 on 2023-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0050_class_traitset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="traitset",
            field=models.CharField(default="NM_2021", max_length=20, null=True),
        ),
    ]
