# Generated by Django 4.2 on 2023-11-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0051_alter_class_traitset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bovine",
            old_name="data",
            new_name="genotype_normals",
        ),
        migrations.RenameField(
            model_name="bovine",
            old_name="scaled",
            new_name="scaled_genotype",
        ),
        migrations.AddField(
            model_name="bovine",
            name="phenotype",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
