# Generated by Django 4.2 on 2023-11-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0052_rename_data_bovine_genotype_normals_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bovine",
            old_name="scaled_genotype",
            new_name="genotype",
        ),
        migrations.RemoveField(
            model_name="bovine",
            name="genotype_normals",
        ),
    ]
