# Generated by Django 4.2 on 2023-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0053_rename_scaled_genotype_bovine_genotype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="viewable_recessives",
            field=models.JSONField(null=True),
        ),
    ]
